version: "3.1"

services:

    # Symfony 7
    nginx_symfony_7:
        image: siapep/nginx-php
        volumes:
            - ./symfony_7:/var/www/app
        ports:
            - 8087:80
        networks:
            - symfony_7_app
        env_file:
            - .env.nginx-php-symfony4.local
    
    php_symfony_7:
        image: siapep/php-84
        volumes:
            - ./symfony_7:/var/www/app
        networks:
            - symfony_7_app
        env_file:
            - .env.php.local

    # Symfony 6
    nginx_symfony_6:
        image: siapep/nginx-php
        volumes:
            - ./symfony_6:/var/www/app
        ports:
            - 8080:80
        networks:
            - symfony_6_app
        env_file:
            - .env.nginx-php-symfony4.local
    
    php_symfony_6:
        image: siapep/php-82
        volumes:
            - ./symfony_6:/var/www/app
        networks:
            - symfony_6_app
        env_file:
            - .env.php.local

    # Symfony 5
    nginx_symfony_5:
        image: siapep/nginx-php
        volumes:
            - ./symfony_5:/var/www/app
        ports:
            - 8081:80
        networks:
            - symfony_5_app
        env_file:
            - .env.nginx-php-symfony4.local
    
    php_symfony_5:
        image: siapep/php-82
        volumes:
            - ./symfony_5:/var/www/app
        networks:
            - symfony_5_app
        env_file:
            - .env.php.local

    # Symfony 4
    nginx_symfony_4:
        image: siapep/nginx-php
        volumes:
            - ./symfony_4:/var/www/app
        ports:
            - 8082:80
        networks:
            - symfony_4_app
        env_file:
            - .env.nginx-php-symfony4.local
    
    php_symfony_4:
        image: siapep/php-82
        volumes:
            - ./symfony_4:/var/www/app
        networks:
            - symfony_4_app
        env_file:
            - .env.php.local

    # Symfony 3
    nginx_symfony_3:
        image: siapep/nginx-php
        volumes:
            - ./symfony_3:/var/www/app
        ports:
            - 8083:80
        networks:
            - symfony_3_app
        env_file:
            - .env.nginx-php-symfony3.local
    
    php_symfony_3:
        image: siapep/php-73
        volumes:
            - ./symfony_3:/var/www/app
        networks:
            - symfony_3_app
        env_file:
            - .env.php.local

    # PHP 8 APP with root file index.php
    nginx_php_8_app:
        image: siapep/nginx-php
        volumes:
            - ./php8:/var/www/app
        ports:
            - 8084:80
        networks:
            - php_8_app
        env_file:
            - .env.nginx-php-app.local
    
    php_php_8_app:
        image: siapep/php-82
        volumes:
            - ./php8:/var/www/app
        networks:
            - php_8_app
        env_file:
            - .env.php.local

    # PHP 7 APP with root file index.php
    nginx_php_7_app:
        image: siapep/nginx-php
        volumes:
            - ./php7:/var/www/app
        ports:
            - 8085:80
        networks:
            - php_7_app
        env_file:
            - .env.nginx-php-app.local
    
    php_php_7_app:
        image: siapep/php-73
        volumes:
            - ./php7:/var/www/app
        networks:
            - php_7_app
        env_file:
            - .env.php.local

    # SPA App
    nginx_spa_app:
        image: siapep/nginx-spa
        volumes:
            - ./spa:/var/www/app
        ports:
            - 8086:80
        env_file:
            - .env.nginx-spa-app.local

networks:
    symfony_7_app:
    symfony_6_app:
    symfony_5_app:
    symfony_4_app:
    symfony_3_app:
    php_8_app:
    php_7_app:
