name: Nginx PHP Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - nginx-php/**    
  pull_request:
    branches: [ "main" ]
    paths:
      - nginx-php/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker build and push
      uses: cloudposse/github-action-docker-build-push@1.11.0
      with:
        workdir: './nginx-php'
        file: 'Dockerfile' # optional, default is Dockerfile
        organization: 'siapep'
        repository: 'nginx-php'
        registry: 'registry.docker.com'
        login: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}